### ISSUE TITLE
I recreate the pretrained feature files with 36 features per image, but the rois num of some images does not have 36? 

### ISSUE THREAD

**Issue by WeiqiuChen** [peteanderson80/bottom-up-attention#39]
I want recreate visual genome feature with   36 features per image.
but I find some images roi nums <36；
how can I make rois nums >=36;
![image](https://user-images.githubusercontent.com/22571609/47070502-f0c60e00-d223-11e8-88d4-10a937d259f8.png)
where the five nums means:
rois.shape, max_conf.shape, np.argsort(max_conf)[::-1].shape,img.h,img.w

roisnum <36,it cannot get 36 features per image.

**Comment by peteanderson80** [comment]
Did you set set `MIN_BOXES=36` and `MAX_BOXES=36` in [generate_tsv.py](https://github.com/peteanderson80/bottom-up-attention/blob/29167f36d9059e6645c05baa3c70e3a040953e85/tools/generate_tsv.py#L38-L39)?

If so it must be because there was not enough candidates at the ROI pooling stage. You could try modifying the [config file](https://github.com/peteanderson80/bottom-up-attention/blob/master/experiments/cfgs/faster_rcnn_end2end_resnet.yml), for example by decreasing `TEST.RPN_NMS_THRESH`.
The set of all default options is [here](https://github.com/peteanderson80/bottom-up-attention/blob/master/lib/fast_rcnn/config.py).

**Comment by peteanderson80** [comment]
(I assume this is not for COCO images or you can just use the pre-extracted features listed in the README).

**Comment by WeiqiuChen** [comment]
yes, I just want to use the model to extract image features from vg dataset.
And I  find there was not enough candidates at the ROI pooling stage.
And I modify the config file  TEST.RPN_NMS_THRESH.  But I increase TEST.RPN_NMS_THRESH, not decrease. The  roi nums just can add.

**Comment by peteanderson80** [comment]
Great! Glad your problem is solved.
