### ISSUE TITLE
I can not download pretrained model

### ISSUE THREAD

**Issue by xpchen0** [peteanderson80/bottom-up-attention#94]
I can not download pretrained model with the link https://www.dropbox.com/s/5xethd2nxa8qrnq/resnet101_faster_rcnn_final.caffemodel?dl=1 . Are there any other links to download? thanks

**Comment by Praying123** [comment]
I have the same problem.Did you have solve it?

**Comment by peteanderson80** [comment]
I just checked this download link and it appears to me to be active and working. Can you describe what error you get?

**Comment by Praying123** [comment]
Dear Peter，
&nbsp; 
I am very surprised to receive your email, because of some internal reasons in China, the download link has been blocked, 
I opened the VPN and download the resources today, thank you very much! 




With kind regards,


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "peteanderson80/bottom-up-attention"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月14日(星期天) 晚上11:37
收件人:&nbsp;"peteanderson80/bottom-up-attention"<bottom-up-attention@noreply.github.com&gt;;
抄送:&nbsp;"喵~"<1666547760@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [peteanderson80/bottom-up-attention] I can not download pretrained model (#94)





 
I just checked this download link and it appears to me to be active and working. Can you describe what error you get?

**Comment by peteanderson80** [comment]
Ok great!

**Comment by Praying123** [comment]
Dear Peter，


I hope I'm not disturbing you.I want to reproduce the attributes and target detection as below. I saw the README.md&nbsp; write the envs is trained under the multi card GPU and needs to install nccl. If my machine only a single GPU, can I implementate the function? At the same time, do I need to install nccl? Looking forward to hearing from you.





With kind regards,


Name: Wenfang Cheng
E-mail:&nbsp;1666547760@qq.com

------------------ 原始邮件 ------------------
发件人:                                                                                                                        "peteanderson80/bottom-up-attention"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月15日(星期一) 凌晨0:01
收件人:&nbsp;"peteanderson80/bottom-up-attention"<bottom-up-attention@noreply.github.com&gt;;
抄送:&nbsp;"喵~"<1666547760@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [peteanderson80/bottom-up-attention] I can not download pretrained model (#94)





 
Ok great!

**Comment by peteanderson80** [comment]
You can extract image features with a single GPU, although for training the model we used 8 gpus. I think you still need nccl.
